---
title: "Best Practices"
---

<style>
div.python pre { background-color: #fdfcff; }
</style>

<style>
div.r pre { background-color: #fffffc; }
</style>





# PEP8

The link below exposes a style guide for python, I strongly recommend that you read these guidelines before sending your project. It will be helpful to improve the readability of the code. 


https://www.python.org/dev/peps/pep-0008/#introduction

Here are a few short quotes from the guide :

- One of Guido's key insights is that code is read much more often than it is written. As PEP 20 says, "Readability counts".

- A style guide is about consistency. Consistency with this style guide is important. Consistency within a project is more important. Consistency within one module or function is the most important.

- Limit all lines to a maximum of 79 characters.

- Spaces are the preferred indentation method.

- Indentation : Use 4 spaces per indentation level, no tabs. Continuation lines should align wrapped elements either vertically using Python's implicit line joining inside parentheses, brackets and braces, or using a hanging indent

```
# Correct:

# Aligned with opening delimiter.
foo = long_function_name(var_one, var_two,
                         var_three, var_four)

``` 

``` 
# Wrong:

# Arguments on first line forbidden when not using vertical alignment.
foo = long_function_name(var_one, var_two,
    var_three, var_four)

``` 



- When the conditional part of an if-statement is long enough to require that it be written across multiple lines:

``` 
# Acceptable

# No extra indentation.
if (this_is_one_thing and
    that_is_another_thing):
    do_something()


# Add some extra indentation on the conditional continuation line.
if (this_is_one_thing
        and that_is_another_thing):
    do_something()

```




- Should a Line Break Before or After a Binary Operator?

``` 
# Wrong:
# operators sit far away from their operands
income = (gross_wages +
          taxable_interest +
          (dividends - qualified_dividends) -
          ira_deduction -
          student_loan_interest)
``` 

```
# Correct:
# easy to match operators with operands
income = (gross_wages
          + taxable_interest
          + (dividends - qualified_dividends)
          - ira_deduction
          - student_loan_interest)

```

- imports :

``` 
# Correct:
import os
import sys

# Correct:
from subprocess import Popen, PIPE

# Wrong:
import sys, os
``` 

- Whitespace in Expressions and Statements :

``` 
# Correct:
spam(ham[1], {eggs: 2})

# Wrong:
spam( ham[ 1 ], { eggs: 2 } )

``` 

```
# Correct:
if x == 4: print x, y; x, y = y, x

# Wrong:
if x == 4 : print x , y ; x , y = y , x
``` 


- More than one space around an assignment (or other) operator to align it with another:

``` 
# Correct:
x = 1
y = 2
long_variable = 3

# Wrong:
x             = 1
y             = 2
long_variable = 3
```


- Operators 

``` 
# Correct:
i = i + 1
submitted += 1
x = x*2 - 1
hypot2 = x*x + y*y
c = (a+b) * (a-b)
``` 

``` 
# Wrong:
i=i+1
submitted +=1
x = x * 2 - 1
hypot2 = x * x + y * y
c = (a + b) * (a - b)
```

- Don't use spaces around the = sign when used to indicate a keyword argument, or when used to indicate a default value for an unannotated function parameter:

``` 
# Correct:
def complex(real, imag=0.0):
    return magic(r=real, i=imag)
```


``` 
# Wrong:
def complex(real, imag = 0.0):
    return magic(r = real, i = imag)
```

- Compound statements (multiple statements on the same line) are generally discouraged:

``` 
# Correct:
if foo == 'blah':
    do_blah_thing()
do_one()
do_two()
do_three()
```

```
# Wrong:
if foo == 'blah': do_blah_thing()
do_one(); do_two(); do_three()
```

- When trailing commas are redundant..the pattern is to put each value (etc.) on a line by itself, always adding a trailing comma, and add the close parenthesis/bracket/brace on the next line. 

```
# Correct:
FILES = [
    'setup.cfg',
    'tox.ini',
    ]
initialize(FILES,
           error=True,
           )
```

```
# Wrong:
FILES = ['setup.cfg', 'tox.ini',]
initialize(FILES, error=True,)
```

- Conventions for writing good documentation strings (a.k.a. "docstrings") are immortalized in PEP 257.  \textbf{Write docstrings for all public modules, functions, classes, and methods.}

``` 
"""Return a foobang

Optional plotz says to frobnicate the bizbaz first.
"""
``` 

```
"""Return an ex-parrot."""

```

- Never use the characters 'l' (lowercase letter el), 'O' (uppercase letter oh), or 'I' (uppercase letter eye) as single character variable names.

- Function names should be lowercase, with words separated by underscores as necessary to improve readability.

-Variable names follow the same convention as function names.

- Constants are usually defined on a module level and written in all capital letters with underscores separating words. Examples include MAX_OVERFLOW and TOTAL.

``` 
PATH = '/my/path'
```


-Use is not operator rather than not ... is. While both expressions are functionally identical, the former is more readable and preferred:

```
# Correct:
if foo is not None:


# Wrong:
if not foo is None:
```


- Always use a def statement instead of an assignment statement that binds a lambda expression directly to an identifier:

```
# Correct:
def f(x): return 2*x


# Wrong:
f = lambda x: 2*x
```


- Additionally, for all try/except clauses, limit the try clause to the absolute minimum amount of code necessary. Again, this avoids masking bugs:

```
# Correct:
try:
    value = collection[key]
except KeyError:
    return key_not_found(key)
else:
    return handle_value(value)
```

```
# Wrong:
try:
    # Too broad!
    return handle_value(collection[key])
except KeyError:
    # Will also catch KeyError raised by handle_value()
    return key_not_found(key)
```


- For sequences, (strings, lists, tuples), use the fact that empty sequences are false:

``` 
# Correct:
if not seq:
if seq:

# Wrong:
if len(seq):
if not len(seq):
```


- Don't compare boolean values to True or False using ==:

```
# Correct:
if greeting:


# Wrong:
if greeting == True:
```



# Rmarkdown

# GitHub

Github is a company that creates products that use the open source tool git.
From wikipédia: "Git is a distributed version-control system for tracking changes in any set of files, originally designed for coordinating work among programmers cooperating on source code during software development.". It was created by Linus Torvalds, the creator of the Linux kernel.